### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by asdf3601a** [OKTW-Network/live-frontend#27]
todo:
 - [x] 把那堆 (.*)Player 拼起來
 - [ ] 不能播放聲音/快轉/倒轉/ ...etc 的提示 (#25, #28)
 - [ ] 播放速度的 Input
 - [ ] 播放器進度條樣式 (#19, #30)
 - [ ] 顯示游標指在時間條上的時間 (#20, #31)
 - [ ] 共同觀看 (#22, #32)
 - [ ] 播放器載入時偵測 pointer type

_Originally posted by @asdf3601a in https://github.com/OKTW-Network/live-frontend/pull/26#pullrequestreview-1785916636_
